<?php

namespace app\api\model;

use think\Model;

class BaseModel extends Model
{
    protected  function prefixImgUrl($value,$data)
    {
        $finalUrl = $value;
        if ($data['from'] == 1)
        {
            $finalUrl = config('setting.img_prefix').$value;
        }
        return $finalUrl;
    }
    public function execute($sql, $bind = [])
    {
        return parent::execute($sql, $bind); // TODO: Change the autogenerated stub
    }
}
