<?php
/**
 * Created by PhpStorm.
 * User: liuyongdong
 * Date: 2018/6/12
 * Time: 21:24
 */

namespace app\api\model;


use think\console\command\make\Model;

class TestTable extends BaseModel
{
    public function aa($method, $args)
    {
//        $SpeModel = new Model(); // 实例化一个model对象 没有对应任何数据表
//        $SpeModel->execute("update think_user set name='thinkPHP' where status=1");
    }
 public function execute($sql, $bind = [])
 {
     return parent::execute($sql, $bind); // TODO: Change the autogenerated stub
 }


}